// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Skill is the predicate function for skill builders.
type Skill func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
