// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Skill is the predicate function for skill builders.
type Skill func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserSkill is the predicate function for userskill builders.
type UserSkill func(*sql.Selector)
