version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - 8080:8080
  client:
    build:
      context: ./client
    ports:
      - 3000:3000
    depends_on:
      - backend