version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - 8080:8080
    environment:
      PASSWORD: pass
      DB_HOST: db
      DB_NAME: test
    depends_on:
      - db
  client:
    build:
      context: ./client
    ports:
      - 80:80
    depends_on:
      - backend
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: test
    ports:
      - 3306:3306