// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/squadra-ricordo/ent/userskill"
)

// UserSkill is the model entity for the UserSkill schema.
type UserSkill struct {
	config
	// ID of the ent.
	ID               int `json:"id,omitempty"`
	user_user_skills *int
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserSkill) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case userskill.FieldID:
			values[i] = new(sql.NullInt64)
		case userskill.ForeignKeys[0]: // user_user_skills
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type UserSkill", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserSkill fields.
func (us *UserSkill) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userskill.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			us.ID = int(value.Int64)
		case userskill.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_user_skills", value)
			} else if value.Valid {
				us.user_user_skills = new(int)
				*us.user_user_skills = int(value.Int64)
			}
		}
	}
	return nil
}

// Update returns a builder for updating this UserSkill.
// Note that you need to call UserSkill.Unwrap() before calling this method if this UserSkill
// was returned from a transaction, and the transaction was committed or rolled back.
func (us *UserSkill) Update() *UserSkillUpdateOne {
	return (&UserSkillClient{config: us.config}).UpdateOne(us)
}

// Unwrap unwraps the UserSkill entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (us *UserSkill) Unwrap() *UserSkill {
	tx, ok := us.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserSkill is not a transactional entity")
	}
	us.config.driver = tx.drv
	return us
}

// String implements the fmt.Stringer.
func (us *UserSkill) String() string {
	var builder strings.Builder
	builder.WriteString("UserSkill(")
	builder.WriteString(fmt.Sprintf("id=%v", us.ID))
	builder.WriteByte(')')
	return builder.String()
}

// UserSkills is a parsable slice of UserSkill.
type UserSkills []*UserSkill

func (us UserSkills) config(cfg config) {
	for _i := range us {
		us[_i].config = cfg
	}
}
