// Code generated by entc, DO NOT EDIT.

package skill

const (
	// Label holds the string label denoting the skill type in the database.
	Label = "skill"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeUserSkills holds the string denoting the user_skills edge name in mutations.
	EdgeUserSkills = "user_skills"
	// Table holds the table name of the skill in the database.
	Table = "skills"
	// UserSkillsTable is the table that holds the user_skills relation/edge.
	UserSkillsTable = "user_skills"
	// UserSkillsInverseTable is the table name for the UserSkill entity.
	// It exists in this package in order to avoid circular dependency with the "userskill" package.
	UserSkillsInverseTable = "user_skills"
	// UserSkillsColumn is the table column denoting the user_skills relation/edge.
	UserSkillsColumn = "skill_user_skills"
)

// Columns holds all SQL columns for skill fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
