// Code generated by entc, DO NOT EDIT.

package userskill

const (
	// Label holds the string label denoting the userskill type in the database.
	Label = "user_skill"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the userskill in the database.
	Table = "user_skills"
)

// Columns holds all SQL columns for userskill fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "user_skills"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_user_skills",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
